In [1]:
import pandas as pd
import numpy as np

In [2]:
#result_path_u1 = 'E:/泰迪杯/数据挖掘2021/模糊综合评价结果/有缺失值/模糊综合评价景区评分utf-8.csv'
#result_path_g1 = 'E:/泰迪杯/数据挖掘2021/模糊综合评价结果/有缺失值/模糊综合评价景区评分gbk.csv'
result_path_u = 'E:/泰迪杯/数据挖掘2021/模糊综合评价结果/模糊综合评价景区评分utf-8.csv'
result_path_g = 'E:/泰迪杯/数据挖掘2021/模糊综合评价结果/模糊综合评价景区评分gbk.csv'

In [3]:
col = ['序号','景区名称','总得分','服务得分','位置得分','设施得分','卫生得分','性价比得分']
rating = pd.DataFrame(columns=col)
for doc_num in range(1,51):
    # 读入数据
    review_path = 'E:/泰迪杯/数据挖掘2021/情感分析结果utf-8/A' + str(doc_num) + 'utf-8.csv'
    reviews = pd.read_csv(review_path, encoding='utf-8')[['评价方面','情感等级']]
    col = {'评价方面':'topic','情感等级':'emotion_level'}
    reviews.rename(columns=col,inplace=True)
    
    # 行名是主题，列名是情感等级，数值是频数
    R_tmp = np.empty(shape=(0,5))
    order = ['服务','位置','设施','卫生','性价比']
    for emotionLevel in range(1,6):
        # 情感等级为emotionLevel的数据表
        level = reviews[reviews['emotion_level'] == emotionLevel]
        print('level ',level)
    
        # 提取在该情感等级下每个评价方面的数量，为向量
        num_arr = level['topic'].value_counts()
        if len(num_arr)>0:
            num_arr = num_arr.reindex(order) # 统一主题顺序为order
            num_arr = num_arr.values
        if len(num_arr)==0: # 向量长度为0
            num_arr = np.zeros((1,5))
    
        # 将向量合并到R中
        R_tmp = np.vstack((R_tmp, num_arr))
    R_tmp = R_tmp.T
    np.nan_to_num(R_tmp, copy=False)  # 将缺失值填充为0
    
    # 计算主题的评价次数
    c = np.array([1,1,1,1,1]).reshape(5,1)
    topic_sum = R_tmp.dot(c)
    
    # 计算评判矩阵R
    R = R_tmp/topic_sum
    print("R = ",R)
    
    # 计算各评价方面的权重矩阵A
    A = (topic_sum/sum(topic_sum)).T
    print("A = ",A)
    
    # 计算模糊综合评价集B
    B = A.dot(R)
    print("B = ",B)
        
    df = {'序号':doc_num, '景区名称':'A'+str(doc_num)}
    level = np.array((5,4,3,2,1))
    df['总得分'] = np.round(level.dot(B.T),1)[0]    # 计算总体满意度
    df['服务得分'] = np.round(level.dot(R[0].T),1)  # 计算服务满意度
    df['位置得分'] = np.round(level.dot(R[1].T),1)  # 计算位置满意度
    df['设施得分'] = np.round(level.dot(R[2].T),1)  # 计算设施满意度
    df['卫生得分'] = np.round(level.dot(R[3].T),1)  # 计算卫生满意度
    df['性价比得分'] = np.round(level.dot(R[4].T),1)  # 计算性价比满意度
    
    rating = rating.append(df,ignore_index=True)

level       topic  emotion_level
4       服务              1
6       设施              1
9      性价比              1
11      设施              1
14     性价比              1
...    ...            ...
4571    位置              1
4572    位置              1
4576   性价比              1
4577    服务              1
4579   性价比              1

[845 rows x 2 columns]
level       topic  emotion_level
18      服务              2
19      设施              2
22      设施              2
23      位置              2
28      设施              2
...    ...            ...
4582    服务              2
4583    服务              2
4587    设施              2
4589    设施              2
4591   性价比              2

[1395 rows x 2 columns]
level       topic  emotion_level
1       服务              3
5      性价比              3
13      服务              3
16      服务              3
20     性价比              3
...    ...            ...
4555    位置              3
4566    服务              3
4574    服务              3
4580    服务              3
4588    设施          

level       topic  emotion_level
15      服务              1
17     性价比              1
101     服务              1
120    性价比              1
133     服务              1
...    ...            ...
3279    位置              1
3282   性价比              1
3447   性价比              1
3460    位置              1
3507   性价比              1

[91 rows x 2 columns]
level       topic  emotion_level
20     性价比              2
30      服务              2
37      位置              2
39      服务              2
47     性价比              2
...    ...            ...
3553    服务              2
3564    服务              2
3565    服务              2
3569    设施              2
3574   性价比              2

[488 rows x 2 columns]
level       topic  emotion_level
0       设施              3
1       服务              3
2       设施              3
8       卫生              3
14      服务              3
...    ...            ...
3562   性价比              3
3567    卫生              3
3568    服务              3
3571    位置              3
3572    服务            

level       topic  emotion_level
1      性价比              1
3       服务              1
6       服务              1
12      服务              1
15      设施              1
...    ...            ...
1806    设施              1
1813    服务              1
1817   性价比              1
1822    位置              1
1861   性价比              1

[211 rows x 2 columns]
level       topic  emotion_level
2       设施              2
21     性价比              2
25      服务              2
33     性价比              2
50      设施              2
...    ...            ...
1699   性价比              2
1704    设施              2
1710    设施              2
1746    设施              2
1791    设施              2

[114 rows x 2 columns]
level       topic  emotion_level
9       位置              3
11     性价比              3
13      服务              3
16     性价比              3
19     性价比              3
...    ...            ...
1862    设施              3
1865   性价比              3
1866    设施              3
1868    卫生              3
1869    服务           

[96 rows x 2 columns]
level      topic  emotion_level
1     性价比              2
10    性价比              2
12     服务              2
18    性价比              2
25     卫生              2
..    ...            ...
978    位置              2
979    服务              2
982   性价比              2
983    服务              2
984    卫生              2

[312 rows x 2 columns]
level      topic  emotion_level
3      服务              3
7      卫生              3
9     性价比              3
11     卫生              3
13     位置              3
..    ...            ...
969   性价比              3
971    服务              3
977   性价比              3
980    卫生              3
985    位置              3

[400 rows x 2 columns]
level      topic  emotion_level
6      服务              4
8      位置              4
16     服务              4
20     服务              4
21     服务              4
..    ...            ...
954    卫生              4
964    服务              4
965    卫生              4
974    卫生              4
981    卫生              4

[112 row

level      topic  emotion_level
32    性价比              1
35    性价比              1
47     服务              1
52     位置              1
61     设施              1
64    性价比              1
68     卫生              1
81     服务              1
89     卫生              1
90     位置              1
95     卫生              1
97     服务              1
98     服务              1
111    位置              1
127   性价比              1
157   性价比              1
159    服务              1
168   性价比              1
186    卫生              1
194    服务              1
236    卫生              1
247    设施              1
252    服务              1
274    服务              1
300   性价比              1
306    服务              1
307    服务              1
311    设施              1
318   性价比              1
327    卫生              1
339   性价比              1
363    卫生              1
370    服务              1
378    服务              1
392    设施              1
398   性价比              1
402   性价比              1
406    卫生              1
423   性价比         

[180 rows x 2 columns]
level      topic  emotion_level
6      设施              3
12     位置              3
13    性价比              3
16     服务              3
19    性价比              3
..    ...            ...
537    设施              3
538   性价比              3
540    设施              3
541    设施              3
543    服务              3

[213 rows x 2 columns]
level      topic  emotion_level
7     性价比              4
10    性价比              4
14     设施              4
37     卫生              4
39     设施              4
40     卫生              4
41    性价比              4
49     设施              4
58     设施              4
61     位置              4
110    卫生              4
111    卫生              4
125    设施              4
146    设施              4
170   性价比              4
171    服务              4
176    设施              4
178    卫生              4
183    设施              4
201    卫生              4
203    设施              4
204    位置              4
220    卫生              4
238    卫生              4
251    设施     

level      topic  emotion_level
27     设施              1
34    性价比              1
41    性价比              1
48     服务              1
51     位置              1
72     位置              1
97     卫生              1
103    位置              1
113    卫生              1
132    服务              1
139    服务              1
140   性价比              1
144   性价比              1
147    服务              1
158    服务              1
169    卫生              1
179    位置              1
193    服务              1
203   性价比              1
228    设施              1
238    服务              1
258    位置              1
262    设施              1
263   性价比              1
267    服务              1
281    位置              1
285    服务              1
290    卫生              1
297   性价比              1
301   性价比              1
level      topic  emotion_level
1     性价比              2
3     性价比              2
4     性价比              2
5      设施              2
6      服务              2
..    ...            ...
295    卫生              2
300    设施  

231   性价比              5
R =  [[0.15384615 0.28205128 0.38461538 0.17948718 0.        ]
 [0.21428571 0.42857143 0.25       0.07142857 0.03571429]
 [0.175      0.225      0.45       0.125      0.025     ]
 [0.         0.46153846 0.26923077 0.11538462 0.15384615]
 [0.18103448 0.25       0.3362069  0.10344828 0.12931034]]
A =  [[0.15662651 0.1124498  0.16064257 0.10441767 0.46586345]]
B =  [[0.16064257 0.29317269 0.34538153 0.11646586 0.08433735]]
level      topic  emotion_level
16     设施              1
18    性价比              1
22     服务              1
35     卫生              1
45     位置              1
47     服务              1
49    性价比              1
51     设施              1
54    性价比              1
62     服务              1
79     设施              1
83     服务              1
84    性价比              1
88    性价比              1
97     设施              1
111    设施              1
113    设施              1
125   性价比              1
136    服务              1
139   性价比              1
142    位置          

In [4]:
rating

序号 景区名称  总得分  服务得分  位置得分  设施得分  卫生得分  性价比得分
0    1   A1  3.3   3.3   3.1   3.4   2.8    3.4
1    2   A2  3.3   3.3   3.1   3.3   3.0    3.4
2    3   A3  2.7   2.9   2.5   3.0   2.1    2.8
3    4   A4  2.8   2.9   2.6   2.9   2.3    2.8
4    5   A5  3.0   2.9   2.9   3.1   2.7    3.1
5    6   A6  2.8   2.8   2.6   2.9   2.2    2.9
6    7   A7  3.4   3.4   3.4   3.5   3.1    3.4
7    8   A8  3.0   3.0   2.8   3.0   2.7    3.2
8    9   A9  3.3   3.4   3.2   3.5   3.1    3.3
9   10  A10  2.7   2.9   2.5   2.7   2.0    2.8
10  11  A11  3.3   3.3   3.3   3.4   3.2    3.5
11  12  A12  3.2   3.3   3.1   3.2   3.1    3.3
12  13  A13  3.2   3.1   3.2   3.3   3.2    3.4
13  14  A14  3.3   3.3   3.2   3.3   3.1    3.4
14  15  A15  3.3   3.4   3.2   3.3   3.1    3.5
15  16  A16  3.3   3.3   3.3   3.2   3.1    3.3
16  17  A17  3.3   3.3   3.2   3.4   3.1    3.5
17  18  A18  3.3   3.4   3.1   3.6   3.1    3.3
18  19  A19  3.3   3.3   3.2   3.4   3.2    3.6
19  20  A20  2.8   2.9   2.7   2.8   2.3    2.9
20  21  A21  3.2   3.2   3.2   3.3   3.1    3.3
21  22  A22  3.3   3.3   3.4   3.3   3.1    3.3
22  23  A23  3.2   3.3   3.1   3.4   2.9    3.5
23  24  A24  3.2   3.2   3.2   3.1   2.8    3.6
24  25  A25  3.2   3.1   3.1   3.1   3.0    3.4
25  26  A26  3.3   3.2   3.4   3.6   3.1    3.3
26  27  A27  3.2   3.3   3.1   3.2   3.0    3.4
27  28  A28  3.0   3.1   2.8   3.0   2.6    3.0
28  29  A29  3.3   3.4   3.3   3.3   3.0    3.5
29  30  A30  3.3   3.4   3.3   3.3   3.1    3.5
30  31  A31  2.6   2.8   2.5   2.8   2.1    2.7
31  32  A32  3.3   3.3   3.2   3.3   3.1    3.4
32  33  A33  3.3   3.3   3.2   3.3   3.3    3.4
33  34  A34  2.8   2.9   2.6   2.7   2.0    3.1
34  35  A35  3.3   3.3   3.2   3.1   3.2    3.4
35  36  A36  3.2   3.3   3.2   3.2   3.1    3.5
36  37  A37  3.2   3.1   3.3   3.3   2.7    3.4
37  38  A38  3.0   3.0   3.1   3.0   2.9    3.3
38  39  A39  3.3   3.4   3.4   3.2   3.1    3.5
39  40  A40  3.2   3.5   3.2   3.1   3.0    3.3
40  41  A41  3.0   3.0   2.9   3.1   2.7    3.2
41  42  A42  3.3   3.2   3.4   3.3   3.1    3.3
42  43  A43  3.1   3.1   3.0   3.0   3.1    3.3
43  44  A44  3.2   3.7   3.3   3.3   3.1    3.1
44  45  A45  3.3   3.8   3.1   3.3   2.8    3.4
45  46  A46  3.3   3.4   3.7   3.4   3.0    3.2
46  47  A47  3.2   3.2   3.2   3.3   2.8    3.6
47  48  A48  3.3   3.4   3.0   3.7   3.0    3.3
48  49  A49  3.1   3.4   3.1   3.0   2.8    3.1
49  50  A50  3.2   3.2   3.5   3.2   3.1    3.1

In [5]:
rating.to_csv(result_path_u, encoding='utf-8', index=False)
rating.to_csv(result_path_g, encoding='gbk' , index=False)